# RHOA HOUSEWIVES
nene = Housewife.find_or_create_by(firstname:"NeNe", lastname:"Leakes", current: true, image:"https://i.pinimg.com/originals/1e/f9/ac/1ef9acae1f3f3bea903b14807d9352ae.png")
sheree = Housewife.find_or_create_by(firstname:"Shereé", lastname:"Whitfield", current: false, image:"https://vignette.wikia.nocookie.net/real-housewives/images/b/b8/Sheree-whitfield-full.png/revision/latest?cb=20151109172034")
kimz = Housewife.find_or_create_by(firstname:"Kim", lastname:"Zolciak-Biermann", current: false, image:"https://i.pinimg.com/originals/1c/3f/12/1c3f12febded638a3172a0fca49f434e.png")
lisawu = Housewife.find_or_create_by(firstname:"Lisa", lastname:"Wu", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2012/lisa-wu-hartwell-full.png")
deshawn = Housewife.find_or_create_by(firstname:"DeShawn", lastname:"Snow", current: false, image:"https://i0.wp.com/allthingsrh.com/wp-content/uploads/2013/10/deshawn-snow-full.png?fit=400%2C600")
kandi = Housewife.find_or_create_by(firstname:"Kandi", lastname:"Burruss", current: true, image:"http://thegospelguru.com/wp-content/uploads/2013/02/kandi-burruss-full-alt.png")
cynthia = Housewife.find_or_create_by(firstname:"Cynthia", lastname:"Bailey", current: true, image:"https://the-hollywood-gossip-res.cloudinary.com/iu/s--emF366yH--/c_scale,f_auto,h_1856,q_auto,w_696/v1422466233/cynthia-bailey-promo-pic")
phaedra = Housewife.find_or_create_by(firstname:"Phaedra", lastname:"Parks", current: false, image:"https://i.ibb.co/WB5wN8y/Phaedra.png")
porsha = Housewife.find_or_create_by(firstname:"Porsha", lastname:"Williams", current: true, image:"https://i.ibb.co/3Wq0Zsg/Porsha.png")
kenya = Housewife.find_or_create_by(firstname:"Kenya", lastname:"Moore", current: true, image:"https://bossip.files.wordpress.com/2015/09/kenya-moore-full.png?w=468&h=1712")
claudia = Housewife.find_or_create_by(firstname:"Claudia", lastname:"Jordan", current: false, image:"https://www.bravotv.com/sites/bravo/files/legacy/images/person/body/2014/claudia-jordan-full.png")
kimf = Housewife.find_or_create_by(firstname:"Kim", lastname:"Fields", current: false, image:"https://www.bravotv.com/sites/bravo/files/field_person_full_photo/2015/09/kim-fields-full.png")
eva = Housewife.find_or_create_by(firstname:"Eva", lastname:"Marcille", current: true, image:"https://i2.wp.com/www.celebrity-cutouts.com/wp-content/uploads/2019/07/eva-marcille-pink-dress-cardboard-cutout.png?resize=450%2C500&ssl=1")
shamari = Housewife.find_or_create_by(firstname:"Shamari", lastname:"DeVoe", current: false, image:"https://i.ibb.co/X4Pk9z4/Shamari.png")
